using System.Collections.Generic;
using System.Linq;
using EXGEPA.Model;

namespace EXGEPA.Transfert.Core.RepositoryHelper
{
    public static class CurrencyLoader

    {

        public static List<Currency> LoadCurrencies()
        {
            var result = new List<Currency>()
            {
                new Currency{Key = "AED",Caption = "Dirham des émirats arabes unis"},
new Currency{Key = "AFN",Caption = "Afghani"},
new Currency{Key = "ALL",Caption = "Lek albanais"},
new Currency{Key = "AMD",Caption = "Dram"},
new Currency{Key = "AOA",Caption = "Kwanza angolais"},
new Currency{Key = "ARS",Caption = "Peso argentin"},
new Currency{Key = "AUD",Caption = "Dollar australien"},
new Currency{Key = "AZN",Caption = "Manat azerbaïdjanais"},
new Currency{Key = "BAM",Caption = "Mark convertible"},
new Currency{Key = "BBD",Caption = "Dollar barbadien"},
new Currency{Key = "BDT",Caption = "Taka"},
new Currency{Key = "BGN",Caption = "Lev bulgare"},
new Currency{Key = "BHD",Caption = "Dinar bahreïni"},
new Currency{Key = "BIF",Caption = "Franc burundais"},
new Currency{Key = "BND",Caption = "Dollar de Brunei"},
new Currency{Key = "BOB",Caption = "Boliviano bolivien"},
new Currency{Key = "BRL",Caption = "Réal brésilien"},
new Currency{Key = "BSD",Caption = "Dollar bahaméen"},
new Currency{Key = "BTN",Caption = "Ngultrum"},
new Currency{Key = "BWP",Caption = "Pula botswanais"},
new Currency{Key = "BYN",Caption = "Rouble biélorusse"},
new Currency{Key = "BZD",Caption = "Dollar bélizien"},
new Currency{Key = "CAD",Caption = "Dollar canadien"},
new Currency{Key = "CDF",Caption = "Franc congolais"},
new Currency{Key = "CHF",Caption = "Franc suisse"},
new Currency{Key = "CLP",Caption = "Peso chilien"},
new Currency{Key = "CNY",Caption = "Yuan"},
new Currency{Key = "COP",Caption = "Peso colombien"},
new Currency{Key = "CRC",Caption = "Colon costaricien"},
new Currency{Key = "CUP",Caption = "Peso cubain"},
new Currency{Key = "CVE",Caption = "Escudo cap-verdien"},
new Currency{Key = "CZK",Caption = "Couronne tchèque"},
new Currency{Key = "DJF",Caption = "Franc de Djibouti"},
new Currency{Key = "DKK",Caption = "Couronne danoise"},
new Currency{Key = "DOP",Caption = "Peso dominicain"},
new Currency{Key = "DZD",Caption = "Dinar algérien"},
new Currency{Key = "EGP",Caption = "Livre égyptienne"},
new Currency{Key = "ERN",Caption = "Nakfa érythréen"},
new Currency{Key = "ETB",Caption = "Birr éthiopien"},
new Currency{Key = "EUR",Caption = "Euro"},
new Currency{Key = "FJD",Caption = "Dollar de Fidji"},
new Currency{Key = "GBP",Caption = "Livre sterling"},
new Currency{Key = "GEL",Caption = "Lari"},
new Currency{Key = "GHS",Caption = "Cedi"},
new Currency{Key = "GMD",Caption = "Dalasi gambien"},
new Currency{Key = "GNF",Caption = "Franc guinéen"},
new Currency{Key = "GTQ",Caption = "Quetzal guatémaltèque"},
new Currency{Key = "GYD",Caption = "Dollar guyanien"},
new Currency{Key = "HNL",Caption = "Lempira hondurien"},
new Currency{Key = "HRK",Caption = "Kuna"},
new Currency{Key = "HTG",Caption = "Gourde haïtienne"},
new Currency{Key = "HUF",Caption = "Forint hongrois"},
new Currency{Key = "IDR",Caption = "Roupie indonésienne"},
new Currency{Key = "INR",Caption = "Roupie indienne"},
new Currency{Key = "IQD",Caption = "Dinar irakien"},
new Currency{Key = "IRR",Caption = "Rial iranien"},
new Currency{Key = "ISK",Caption = "Couronne islandaise"},
new Currency{Key = "JMD",Caption = "Dollar jamaïcain"},
new Currency{Key = "JOD",Caption = "Dinar jordanien"},
new Currency{Key = "JPY",Caption = "Yen"},
new Currency{Key = "KES",Caption = "Shilling kényan"},
new Currency{Key = "KGS",Caption = "Som"},
new Currency{Key = "KHR",Caption = "Riel"},
new Currency{Key = "KMF",Caption = "Franc comorien"},
new Currency{Key = "KPW",Caption = "Won nord-coréen"},
new Currency{Key = "KRW",Caption = "Won sud-coréen"},
new Currency{Key = "KWD",Caption = "Dinar koweïtien"},
new Currency{Key = "KZT",Caption = "Tenge"},
new Currency{Key = "LAK",Caption = "Kip"},
new Currency{Key = "LBP",Caption = "Livre libanaise"},
new Currency{Key = "LKR",Caption = "Roupie srilankaise"},
new Currency{Key = "LRD",Caption = "Dollar libérien"},
new Currency{Key = "LSL",Caption = "Loti lesothan"},
new Currency{Key = "LYD",Caption = "Dinar libyen"},
new Currency{Key = "MAD",Caption = "Dirham marocain"},
new Currency{Key = "MDL",Caption = "Leu moldave"},
new Currency{Key = "MGA",Caption = "Ariary malgache"},
new Currency{Key = "MKD",Caption = "Denar"},
new Currency{Key = "MMK",Caption = "Kyat"},
new Currency{Key = "MNT",Caption = "Tugrik"},
new Currency{Key = "MRO",Caption = "Ouguiya mauritanien"},
new Currency{Key = "MUR",Caption = "Roupie mauricienne"},
new Currency{Key = "MVR",Caption = "Rufiyaa"},
new Currency{Key = "MWK",Caption = "Kwacha malawien"},
new Currency{Key = "MXN",Caption = "Peso mexicain"},
new Currency{Key = "MYR",Caption = "Ringgit"},
new Currency{Key = "MZN",Caption = "Metical mozambicain"},
new Currency{Key = "NAD",Caption = "Dollar namibien"},
new Currency{Key = "NGN",Caption = "Naira nigérian"},
new Currency{Key = "NIO",Caption = "Córdoba nicaraguayen"},
new Currency{Key = "NOK",Caption = "Couronne norvégienne"},
new Currency{Key = "NPR",Caption = "Roupie népalaise"},
new Currency{Key = "NZD",Caption = "Dollar néo-zélandais"},
new Currency{Key = "OMR",Caption = "Rial omanais"},
new Currency{Key = "PAB",Caption = "Balboa panaméen"},
new Currency{Key = "PEN",Caption = "Nuevo sol péruvien"},
new Currency{Key = "PGK",Caption = "Kina"},
new Currency{Key = "PHP",Caption = "Peso philippin"},
new Currency{Key = "PKR",Caption = "Roupie pakistanaise"},
new Currency{Key = "PLN",Caption = "Zloty polonais"},
new Currency{Key = "PYG",Caption = "Guaraní paraguayen"},
new Currency{Key = "QAR",Caption = "Riyal qatari"},
new Currency{Key = "RON",Caption = "Leu roumain"},
new Currency{Key = "RSD",Caption = "Dinar serbe"},
new Currency{Key = "RUB",Caption = "Rouble russe"},
new Currency{Key = "RWF",Caption = "Franc rwandais"},
new Currency{Key = "SAR",Caption = "Riyal saoudien"},
new Currency{Key = "SBD",Caption = "Dollar des îles Salomon"},
new Currency{Key = "SCR",Caption = "Roupie seychelloise"},
new Currency{Key = "SDG",Caption = "Livre soudanaise"},
new Currency{Key = "SEK",Caption = "Couronne suédoise"},
new Currency{Key = "SGD",Caption = "Dollar de Singapour"},
new Currency{Key = "SLL",Caption = "Leone sierra-léonais"},
new Currency{Key = "SOS",Caption = "Shilling somalien"},
new Currency{Key = "SRD",Caption = "Dollar de Surinam"},
new Currency{Key = "SSP",Caption = "Livre sud-soudanaise"},
new Currency{Key = "STD",Caption = "Dobra santoméen"},
new Currency{Key = "SYP",Caption = "Livre syrienne"},
new Currency{Key = "SZL",Caption = "Lilangeni swazilandais"},
new Currency{Key = "THB",Caption = "Baht"},
new Currency{Key = "TJS",Caption = "Somoni"},
new Currency{Key = "TMT",Caption = "Manat turkmène"},
new Currency{Key = "TND",Caption = "Dinar tunisien"},
new Currency{Key = "TOP",Caption = "Pa'anga"},
new Currency{Key = "TRY",Caption = "Livre turque"},
new Currency{Key = "TTD",Caption = "Dollar trinidadien"},
new Currency{Key = "TWD",Caption = "Nouveau dollar de Taïwan"},
new Currency{Key = "TZS",Caption = "Shilling tanzanien"},
new Currency{Key = "UAH",Caption = "Hryvnia"},
new Currency{Key = "UGX",Caption = "Shilling ougandais"},
new Currency{Key = "USD",Caption = "Dollar américain"},
new Currency{Key = "UYU",Caption = "Peso uruguayen"},
new Currency{Key = "UZS",Caption = "Sum"},
new Currency{Key = "VEF",Caption = "Bolívar vénézuélien"},
new Currency{Key = "VND",Caption = "Dong"},
new Currency{Key = "VUV",Caption = "Vatu"},
new Currency{Key = "WST",Caption = "Tala"},
new Currency{Key = "XAF",Caption = "Franc CFA"},
new Currency{Key = "XCD",Caption = "Dollar des Caraïbes orientales"},
new Currency{Key = "XOF",Caption = "Franc CFA"},
new Currency{Key = "YER",Caption = "Rial yéménite"},
new Currency{Key = "ZAR",Caption = "Rand sud-africain"},
new Currency{Key = "ZMW",Caption = "Kwacha zambien"}
            };
            result.ForEach(x => x.Caption = x.Caption.ToUpperInvariant());
            return result.OrderBy(x => x.Key).ToList();
        }
    }
}
